### ISSUE TITLE
MCTS tree visualizer front-end

### ISSUE THREAD

**Issue by dmorrill10** [ryanbhayward/games-puzzles-algorithms#38]
I will post some sample MCTS data here while I finish the server.

**Comment by awwong1** [comment]
Probably should have looked at this earlier... The MCTS agent's to_dict method returns something that looks like this:

One parent node with 143 immediate children. Not a particularly useful tree. This doesn't match with the sample data provided?

```
{
  "num_visits": 1,
  "children": [
    {
      "num_visits": 0,
      "action": 0,
      "avg_reward": 0
    },
    {
      "num_visits": 1,
      "action": 1,
      "avg_reward": -1
    },
    {
      "num_visits": 0,
      "action": 2,
      "avg_reward": 0
    },
    // this goes on for 143 actions ...
    {
      "num_visits": 0,
      "action": 143,
      "avg_reward": 0
    }
  ],
  "avg_reward": 1,
  "player": 1
}
```

**Comment by dmorrill10** [comment]
If only one rollout is done (the root's `num_visits` is 1) then this is the tree you would expect on a 12x12 board. I think this is the default setting for MCTS. The web server should probably set something more reasonable for the web app like search for 5 seconds.

**Comment by awwong1** [comment]
Sure. The problem is I made a bad assumption and I assumed that the tree would be binary. It is designed to handle any number of children, but when rendering 100+, they all get squished together.

Visualizer now just looks like a black triangle. (Setting the search time to be 5 seconds just makes a large black triangle)

<img width="673" alt="screen shot 2016-08-16 at 7 52 28 pm" src="https://cloud.githubusercontent.com/assets/2760111/17721970/932b3caa-63eb-11e6-9ddd-56c1d3d8cabe.png">

I'll look into this some more.

**Comment by dmorrill10** [comment]
Ah, yeah, definitely they won't be binary. But one thing you can do is ignore nodes with zero visits, that should prune the tree a lot.

**Comment by awwong1** [comment]
I removed the functionality for dynamic collapsing, it simply wasn't doable with a tree of our size. I pruned the tree to remove all nodes with 0 visits beforehand. Here is what the visualizer returns now for a typical game of hex on the default board size:
<img width="553" alt="screen shot 2016-08-30 at 3 36 55 pm" src="https://cloud.githubusercontent.com/assets/2760111/18108077/e7c06e02-6ec7-11e6-8321-efecd23f4e9f.png">
